create table if not exists public.team_members (
    id bigint generated by default as identity primary key,
    name text not null unique,
    display_name text,
    email text unique,
    role text,
    allowed_sectors text,
    can_manage_records boolean not null default false,
    permission_level text not null default 'full',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.team_members
add column if not exists display_name text;

alter table public.team_members
add column if not exists email text;

alter table public.team_members
add column if not exists allowed_sectors text;

alter table public.team_members
add column if not exists can_manage_records boolean not null default false;

alter table public.team_members
add column if not exists permission_level text not null default 'full';

create unique index if not exists idx_team_members_email_unique
on public.team_members(email)
where email is not null and email <> '';

create table if not exists public.clients (
    id bigint generated by default as identity primary key,
    normalized_name text not null unique,
    full_name text not null,
    group_name text,
    meeting_status text,
    complexity_level text,
    tax_status text,
    assigned_preparer text,
    post_filing_status text,
    documentation_status text,
    preparation_queue_status text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.clients
add column if not exists preparation_queue_status text;

create table if not exists public.client_private (
    client_id bigint primary key references public.clients(id) on delete cascade,
    cpf text,
    phone text,
    gov_password text,
    has_digital_certificate boolean not null default false,
    power_of_attorney text,
    notes text,
    updated_at timestamptz not null default now()
);

alter table public.client_private
add column if not exists has_digital_certificate boolean not null default false;

create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete cascade,
    document_type text,
    institution text,
    status text,
    last_update date,
    control_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.contact_log (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete cascade,
    contact_date timestamptz not null,
    channel text,
    subject text,
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists public.declaration_checkpoints (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete cascade,
    step_key text not null,
    step_label text not null,
    completed boolean not null default false,
    note text,
    updated_by text,
    updated_at timestamptz not null default now(),
    unique (client_id, step_key)
);

create table if not exists public.daily_snapshots (
    id bigint generated by default as identity primary key,
    reference_date date not null unique,
    declaracoes integer not null default 0,
    transmitidas integer not null default 0,
    em_revisao integer not null default 0,
    clientes_com_alguma_documentacao integer not null default 0,
    clientes_docs_completos integer not null default 0,
    clientes_docs_parciais integer not null default 0,
    clientes_sem_documentacao integer not null default 0,
    pct_transmitidas numeric(5,2) not null default 0,
    pct_docs_completos numeric(5,2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_clients_tax_status on public.clients(tax_status);
create index if not exists idx_clients_assigned_preparer on public.clients(assigned_preparer);
create index if not exists idx_clients_documentation_status on public.clients(documentation_status);
create index if not exists idx_clients_preparation_queue_status on public.clients(preparation_queue_status);
create index if not exists idx_documents_client_id on public.documents(client_id);
create index if not exists idx_declaration_checkpoints_client_id on public.declaration_checkpoints(client_id);
create index if not exists idx_daily_snapshots_reference_date on public.daily_snapshots(reference_date);
