# Generated by Django 6.0.5 on 2026-05-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=180)),
                ('meeting_status', models.CharField(blank=True, max_length=120)),
                ('complexity_level', models.CharField(blank=True, max_length=80)),
                ('tax_status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRONTO PARA PREENCHER', 'Pronto para preencher'), ('EM PREENCHIMENTO', 'Em preenchimento'), ('PRONTO PARA REVISÃO', 'Pronto para revisão'), ('AJUSTE - HEVERTON', 'Ajuste - Heverton'), ('AGUARDANDO REUNIÃO', 'Aguardando reunião'), ('TRANSMITIDO', 'Transmitido'), ('SEM STATUS', 'Sem status')], default='PENDENTE', max_length=80)),
                ('assigned_preparer', models.CharField(blank=True, default='Não atribuído', max_length=120)),
                ('post_filing_status', models.CharField(blank=True, max_length=120)),
                ('documentation_status', models.CharField(choices=[('Sem documentação', 'Sem documentação'), ('Recebido parcial', 'Recebido parcial'), ('Recebido total', 'Recebido total')], default='Sem documentação', max_length=80)),
                ('preparation_queue_status', models.CharField(choices=[('Pronta para Preenchimento', 'Pronta para preenchimento'), ('Aguardando documentação', 'Aguardando documentação')], default='Aguardando documentação', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPrivate',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='private_data', serialize=False, to='clients.client')),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('gov_password', models.CharField(blank=True, max_length=255)),
                ('has_digital_certificate', models.BooleanField(default=False)),
                ('power_of_attorney', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_private',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tax_status'], name='clients_tax_sta_6b300b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_preparer'], name='clients_assigne_1fae8f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['documentation_status'], name='clients_documen_e325e3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['preparation_queue_status'], name='clients_prepara_41f865_idx'),
        ),
    ]
