# Generated by Django 6.0.5 on 2026-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('allowed_sectors', models.CharField(blank=True, max_length=255)),
                ('can_manage_records', models.BooleanField(default=False)),
                ('permission_level', models.CharField(choices=[('full', 'Acesso completo'), ('status_only', 'Status e responsável'), ('read_only', 'Somente consulta')], default='full', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['name'],
            },
        ),
    ]
