# Generated by Django 6.0.5 on 2026-05-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField()),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'db_table': 'contact_log',
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Despesas Dedutíveis', 'Despesas dedutíveis'), ('Informe de Rendimentos', 'Informe de rendimentos'), ('Informes Bancários', 'Informes bancários')], max_length=120)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('SOLICITAR DOCUMENTO', 'Solicitar documento'), ('SEM STATUS', 'Sem status')], default='PENDENTE', max_length=80)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('control_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['client__full_name', 'document_type', 'institution'],
                'indexes': [models.Index(fields=['client'], name='documents_client__4ad244_idx'), models.Index(fields=['status'], name='documents_status_f31a08_idx')],
            },
        ),
    ]
