# Generated by Django 6.0.5 on 2026-05-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(unique=True)),
                ('declaracoes', models.PositiveIntegerField(default=0)),
                ('transmitidas', models.PositiveIntegerField(default=0)),
                ('em_revisao', models.PositiveIntegerField(default=0)),
                ('clientes_com_alguma_documentacao', models.PositiveIntegerField(default=0)),
                ('clientes_docs_completos', models.PositiveIntegerField(default=0)),
                ('clientes_docs_parciais', models.PositiveIntegerField(default=0)),
                ('clientes_sem_documentacao', models.PositiveIntegerField(default=0)),
                ('pct_transmitidas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pct_docs_completos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_snapshots',
                'ordering': ['-reference_date'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=120)),
                ('step_label', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='clients.client')),
            ],
            options={
                'db_table': 'declaration_checkpoints',
                'ordering': ['client__full_name', 'step_key'],
                'indexes': [models.Index(fields=['client'], name='declaration_client__f0c4e3_idx'), models.Index(fields=['step_key'], name='declaration_step_ke_0b1abb_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'step_key'), name='unique_client_checkpoint_step')],
            },
        ),
    ]
